dist: trusty
language: c
sudo:required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
      - llvm-5.0
      - llvm-5.0-dev
      - lld-5.0
      - liblz4-dev
before_script:
  - git clone https://github.com/reswitched/unicorn.git
  - cd unicorn
  - UNICORN_ARCHS="aarch64" ./make.sh
  - sudo ./make.sh install
  - cd ..
  - git clone https://github.com/reswitched/Mephisto.git
  - cd Mephisto
  - sudo pip2 install -r requirements.txt
  - make
  - cd ..
  - sudo pip2 install -r requirements.txt
script:  make LD=ld.lld-5.0 && make run_tests MEPHISTO=./Mephisto/ctu
